name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Replace GitHub token
      run: |
        if [ -f "config.js" ]; then
          sed -i "s/YOUR_TOKEN_HERE/${{ secrets.PORTFOLIO_TOKEN }}/g" config.js
        else
          echo "config.js not found, creating from template"
          cp config-template.js config.js
          sed -i "s/YOUR_TOKEN_HERE/${{ secrets.PORTFOLIO_TOKEN }}/g" config.js
        fi
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./