name: Update Traffic Data

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  update-traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Traffic Data
        run: |
          TRAFFIC=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/traffic/views" | \
            jq '.count')
          echo "{\"views\": $TRAFFIC, \"updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > public/traffic.json
          
      - name: Commit Traffic Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/traffic.json
          git commit -m "Update traffic data" || exit 0
          git push
          
      - name: Keep only 2 latest builds
        uses: actions/github-script@v6
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update-traffic.yml',
              per_page: 100
            });
            
            const toDelete = runs.data.workflow_runs.slice(2);
            for (const run of toDelete) {
              await github.rest.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }